# Generated by Django 4.2.1 on 2024-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VIP', 'VIP'), ('NVIP', 'NON_VIP'), ('BC', 'BOOT_CAMP')], max_length=4)),
                ('processor', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('graphics_card', models.CharField(max_length=255)),
                ('vram', models.CharField(max_length=255)),
            ],
        ),
    ]
