# Generated by Django 4.2.1 on 2024-05-27 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.DeleteModel(
            name='TempUser',
        ),
        migrations.AddField(
            model_name='computer',
            name='hours_cost',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computer',
            name='category',
            field=models.CharField(choices=[('STD', 'STANDARD'), ('VIP', 'VIP'), ('BTC', 'BOOTCAMP')], max_length=4),
        ),
        migrations.AddField(
            model_name='review',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.computer', verbose_name='Компьютер'),
        ),
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.review', verbose_name='Родитель'),
        ),
    ]
